# fly.toml app configuration file generated for pkbow-notas on 2024-06-18T18:57:59-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pkbow-notas'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
